from uuid import UUID
from pydantic import BaseModel
from typing import List
from datetime import datetime
from typing import Optional


class Message(BaseModel):
    user_prompt: str
    bot_response: str
    time_created: str  # ISO 8601 string


class Chat(BaseModel):
    chat_id: Optional[UUID]  # Generated by Supabase
    created_at: Optional[datetime]  # Set by Supabase
    last_changed: Optional[datetime]  # Set by Supabase
    conversation: List[Message]
    
